### ISSUE TITLE
Stuck at Dot is Typing

### ISSUE THREAD

**Issue by fahdmirza** [alexpinel/Dot#20]
Hello,
  I have installed Dot on windows server 2022 . It gets installed successfully from exe and starts up. Both in BIGDOT and DocChat, whether I select a document or not, as response to any prompt, it just gets stuck in Dot is Typing. It has downloaded phi-3 model, I also downloaded llama3.1 and tried with it but same behavior. I have GPU, cuda installed. Please advise.
Thanks.

**Comment by creat1c** [comment]
I might have had the same issue. Running in a console window shows some FAISS related error:

```
> Python Path: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\python.exe
> IPC Setup Starting
> Failed to create main window
> IPC Message Received: Initiate Download
> File already exists, no download needed.
> File already exists, no download needed.
> Current working directory: <<REDACTED>>\AppData\Local\Programs\dot
> Python Script Error: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\__init__.py:29: UserWarning: Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.
>   warnings.warn(
> 
> stderr: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\__init__.py:29: UserWarning: Importing PromptTemplate from langchain root module is no longer supported. Please use langchain.prompts.PromptTemplate instead.
>   warnings.warn(
> 
> Python Script Error: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\embeddings\__init__.py:29: LangChainDeprecationWarning: Importing embeddings from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
> 
> `from langchain_community.embeddings import HuggingFaceEmbeddings`.
> 
> To install langchain-community run `pip install -U langchain-community`.
>   warnings.warn(
> 
> stderr: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\embeddings\__init__.py:29: LangChainDeprecationWarning: Importing embeddings from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
> 
> `from langchain_community.embeddings import HuggingFaceEmbeddings`.
> 
> To install langchain-community run `pip install -U langchain-community`.
>   warnings.warn(
> 
> Python Script Error: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\vectorstores\__init__.py:35: LangChainDeprecationWarning: Importing vector stores from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
> `from langchain_community.vectorstores import FAISS`.
> 
> To install langchain-community run `pip install -U langchain-community`.
>   warnings.warn(
> 
> stderr: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\vectorstores\__init__.py:35: LangChainDeprecationWarning: Importing vector stores from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
> 
> `from langchain_community.vectorstores import FAISS`.
> 
> To install langchain-community run `pip install -U langchain-community`.
>   warnings.warn(
> 
> Python Script Error: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\document_loaders\__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
> 
> `from langchain_community.document_loaders import PyPDFLoader`.
> 
> To install langchain-community run `pip install -U langchain-community`.
>   warnings.warn(
> <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\document_loaders\__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
> 
> `from langchain_community.document_loaders import DirectoryLoader`.
> 
> To install langchain-community run `pip install -U langchain-community`.
>   warnings.warn(
> 
> stderr: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\document_loaders\__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
> 
> `from langchain_community.document_loaders import PyPDFLoader`.
> 
> To install langchain-community run `pip install -U langchain-community`.
>   warnings.warn(
> <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\document_loaders\__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
> 
> `from langchain_community.document_loaders import DirectoryLoader`.
> 
> To install langchain-community run `pip install -U langchain-community`.
>   warnings.warn(
> 
> Python Script Error: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\llms\__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
> 
> `from langchain_community.llms import LlamaCpp`.
> 
> To install langchain-community run `pip install -U langchain-community`.
>   warnings.warn(
> 
> stderr: <<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain\llms\__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
> 
> `from langchain_community.llms import LlamaCpp`.
> 
> To install langchain-community run `pip install -U langchain-community`.
>   warnings.warn(
> 
> Python Script Error: Traceback (most recent call last):
>   File "<<REDACTED>>\AppData\Local\Programs\dot\resources\llm\scripts\docdot.py", line 67, in <module>
> 
> stderr: Traceback (most recent call last):
>   File "<<REDACTED>>\AppData\Local\Programs\dot\resources\llm\scripts\docdot.py", line 67, in <module>
> 
> Python Script Error:     vector_store = FAISS.load_local(os.path.join(folder_path, "Dot-data"), embeddings)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 1058, in load_local
>     index = faiss.read_index(
>             ^^^^^^^^^^^^^^^^^
>   File "<<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\faiss\swigfaiss.py", line 9795, in read_index
>     return _swigfaiss.read_index(*args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open <<REDACTED>>\Documents\Dot-Data\Dot-data\index.faiss for reading: No such file or directory
> 
> stderr:     vector_store = FAISS.load_local(os.path.join(folder_path, "Dot-data"), embeddings)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 1058, in load_local
>     index = faiss.read_index(
>             ^^^^^^^^^^^^^^^^^
>   File "<<REDACTED>>\AppData\Local\Programs\dot\resources\llm\python\Lib\site-packages\faiss\swigfaiss.py", line 9795, in read_index
>     return _swigfaiss.read_index(*args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open <<REDACTED>>\Documents\Dot-Data\Dot-data\index.faiss for reading: No such file or directory
```

**Comment by creat1c** [comment]
Also this only occurs in the doc dot mode. Big dot yields a somewhat different error.

**Comment by anikiforov** [comment]
See if this helps: https://github.com/alexpinel/Dot/issues/22#issuecomment-2500134620 - I've made Dot 0.9.2 work on Windows 11 using the Mistral model.
